# Airflow DAG Template for Data Products
# Generated by Agentic Data Product Builder

from datetime import datetime, timedelta
from airflow import DAG
from airflow.operators.python import PythonOperator
from airflow.operators.bash import BashOperator
from airflow.utils.dates import days_ago

# DAG Configuration
DAG_ID = "Customer_Orders_By_Region_v1_0_0"
DESCRIPTION = "Data product for  analysis of customer orders."
SCHEDULE_INTERVAL = "0 6 * * *"
DATA_PRODUCT_ID = "Customer_Orders_By_Region_1_0_0"
DATA_PRODUCT_VERSION = "1.0.0"

# Default arguments
default_args = {
    'owner': 'Agentic Builder',
    'depends_on_past': False,
    'email_on_failure': True,
    'email_on_retry': False,
    'retries': 3,
    'retry_delay': timedelta(minutes=5),
}

# Create DAG
dag = DAG(
    DAG_ID,
    default_args=default_args,
    description=DESCRIPTION,
    schedule_interval=SCHEDULE_INTERVAL,
    start_date=days_ago(1),
    catchup=False,
    tags=['data_product', 'Customer Orders By Region'],
)


def validate_source_freshness(**context):
    """Validate that source datasets are fresh enough"""
    import sys
    sys.path.insert(0, '/Users/anshulparmar/Documents/Personal/MTech/Dissertation/Projects/mvp-1')
    
    from src.utils.data_quality import check_source_freshness
    
    datasets = []
    
    for dataset in datasets:
        is_fresh = check_source_freshness(dataset)
        if not is_fresh:
            raise ValueError(f"Source dataset {dataset} is not fresh enough")
    
    print(f"✅ All {len(datasets)} source datasets are fresh")
    return True


def execute_transformation(**context):
    """Execute the data transformation"""
    import sys
    sys.path.insert(0, '/Users/anshulparmar/Documents/Personal/MTech/Dissertation/Projects/mvp-1')
    
    import duckdb
    
    # Read SQL from file or inline
    sql = """"""
    
    # Execute transformation
    conn = duckdb.connect('data/warehouse.db')
    conn.execute(sql)
    conn.close()
    
    print("✅ SQL transformation executed successfully")
    
    return True


def run_quality_checks(**context):
    """Run data quality checks"""
    import sys
    sys.path.insert(0, '/Users/anshulparmar/Documents/Personal/MTech/Dissertation/Projects/mvp-1')
    
    from src.utils.data_quality import execute_quality_rules
    
    quality_rules = []
    target_table = "gold.customer_orders_by_region"
    
    results = execute_quality_rules(target_table, quality_rules)
    
    failed_rules = [r for r in results if r['status'] == 'failed']
    
    if failed_rules:
        print(f"❌ {len(failed_rules)} quality checks failed")
        for rule in failed_rules:
            print(f"  - {rule['rule_id']}: {rule['message']}")
        raise ValueError("Quality checks failed")
    
    print(f"✅ All {len(results)} quality checks passed")
    return results


def update_registry_metadata(**context):
    """Update data product registry with execution metadata"""
    import sys
    import requests
    from datetime import datetime
    
    sys.path.insert(0, '/Users/anshulparmar/Documents/Personal/MTech/Dissertation/Projects/mvp-1')
    
    execution_date = context['ds']
    task_instance = context['task_instance']
    
    # Get execution metrics
    duration_ms = int((datetime.now() - task_instance.start_date).total_seconds() * 1000)
    
    # Update registry
    payload = {
        "version": DATA_PRODUCT_VERSION,
        "status": "success",
        "duration_ms": duration_ms,
        "rows_processed": context.get('rows_processed', 0),
        "rows_output": context.get('rows_output', 0),
        "quality_check_results": context.get('quality_results', {})
    }
    
    response = requests.post(
        f"http://localhost:8001/api/v1/registry/data-products/{DATA_PRODUCT_ID}/executions",
        json=payload
    )
    
    if response.status_code == 201:
        print("✅ Registry updated successfully")
    else:
        print(f"⚠️  Failed to update registry: {response.text}")
    
    return True


# Task 1: Validate source data freshness
validate_sources = PythonOperator(
    task_id='validate_source_freshness',
    python_callable=validate_source_freshness,
    dag=dag,
)

# Task 2: Execute transformation
transform = PythonOperator(
    task_id='execute_transformation',
    python_callable=execute_transformation,
    dag=dag,
)

# Task 3: Run quality checks
quality_check = PythonOperator(
    task_id='run_quality_checks',
    python_callable=run_quality_checks,
    dag=dag,
)

# Task 4: Update metadata
update_metadata = PythonOperator(
    task_id='update_registry_metadata',
    python_callable=update_registry_metadata,
    dag=dag,
)

# Define task dependencies
validate_sources >> transform >> quality_check >> update_metadata