#!/bin/bash
# Cron Job for Data Product: Daily Revenue By Region Category
# Generated by Agentic Data Product Builder
# Schedule: 00 6 * * *

set -e

# Configuration
DATA_PRODUCT_ID="Daily_Revenue_By_Region_Category_1_0_0"
DATA_PRODUCT_VERSION="1.0.0"
EXECUTION_DATE=$(date +%Y-%m-%d)
LOG_FILE="/Users/anshulparmar/Documents/Personal/MTech/Dissertation/Projects/mvp-1/logs/data_products/Daily Revenue By Region Category_${EXECUTION_DATE}.log"
PROJECT_ROOT="/Users/anshulparmar/Documents/Personal/MTech/Dissertation/Projects/mvp-1"

# Ensure log directory exists
mkdir -p "/Users/anshulparmar/Documents/Personal/MTech/Dissertation/Projects/mvp-1/logs/data_products"

{
    echo "=========================================="
    echo "Data Product: Daily Revenue By Region Category"
    echo "Execution Date: ${EXECUTION_DATE}"
    echo "Started at: $(date)"
    echo "=========================================="
    
    # Step 1: Validate source data freshness
    echo ""
    echo "[1/4] Validating source data freshness..."
    python3 "${PROJECT_ROOT}/src/utils/validate_sources.py" \
        --datasets 
    
    if [ $? -ne 0 ]; then
        echo "❌ Source validation failed"
        exit 1
    fi
    echo "✅ Source validation passed"
    
    # Step 2: Execute transformation
    echo ""
    echo "[2/4] Executing transformation..."
    duckdb data/warehouse.db < "${PROJECT_ROOT}/sql/Daily Revenue By Region Category.sql"
    
    if [ $? -ne 0 ]; then
        echo "❌ Transformation failed"
        exit 1
    fi
    echo "✅ Transformation completed"
    
    # Step 3: Run quality checks
    echo ""
    echo "[3/4] Running quality checks..."
    python3 "${PROJECT_ROOT}/src/utils/quality_check.py" \
        --data-product-id "${DATA_PRODUCT_ID}" \
        --target-table "gold.daily_revenue_by_region_category"
    
    if [ $? -ne 0 ]; then
        echo "❌ Quality checks failed"
        exit 1
    fi
    echo "✅ Quality checks passed"
    
    # Step 4: Update registry
    echo ""
    echo "[4/4] Updating registry..."
    curl -X POST "http://localhost:8001/api/v1/registry/data-products/${DATA_PRODUCT_ID}/executions" \
        -H "Content-Type: application/json" \
        -d "{
            \"version\": \"${DATA_PRODUCT_VERSION}\",
            \"status\": \"success\",
            \"execution_date\": \"${EXECUTION_DATE}\"
        }"
    
    echo ""
    echo "=========================================="
    echo "✅ Execution completed successfully"
    echo "Finished at: $(date)"
    echo "=========================================="
    
} >> "$LOG_FILE" 2>&1

# Check exit status
if [ $? -eq 0 ]; then
    echo "✅ Data product execution successful. Log: $LOG_FILE"
    exit 0
else
    echo "❌ Data product execution failed. Check log: $LOG_FILE"
    exit 1
fi